message:
  channel: "dingding"
  dingding:
    webhook: "https://oapi.dingtalk.com/robot/send?access_token=508dc9040f4660229b6ae96eb02c64c3cebba080518be08db481fc3f931467f4"
    secret: "SEC6d00bdfed15181ef1c93c6f4527893269656847cd55f248cefc6a4d3b327b1ce"
  wecom:
    webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=YOUR_KEY"

monitor:
  mysql:
    - name: "mysql_master"
      host: "10.210.3.14"
      port: 3326
      user: "root"
      password: "kX<sMu#Si9pt"
  redis:
    - name: "redis_cache"
      host: "127.0.0.1"
      port: 6379
      db: 0
      password: ""
  oracle:
    - name: "oracle_test"
      host: "127.0.0.1"
      port: 1521
      service_name: "orclpdb1"
      user: "scott"
      password: "tiger"
